# Generated by Django 2.0.1 on 2018-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('user', models.IntegerField(choices=[(1, '管理员'), (2, '普通用户'), (3, 'VIP用户')], verbose_name='用户类型')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('brief', models.CharField(blank=True, max_length=140, null=True, verbose_name='个人简历')),
                ('sex', models.IntegerField(choices=[(1, '男'), (0, '女')], default=1, verbose_name='性别')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('code', models.CharField(max_length=4, verbose_name='验证码')),
                ('stime', models.TimeField(auto_now=True, verbose_name='生效时间')),
                ('status', models.IntegerField(verbose_name='激活状态')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='./static/img/user_pic', verbose_name='头像')),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='app01.UserProfile', verbose_name='我的粉丝')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'db_table': 'UserProfile',
            },
        ),
    ]
