# Generated by Django 2.0.1 on 2018-02-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=4, verbose_name='验证码')),
                ('stime', models.TimeField(auto_now=True, verbose_name='生效时间')),
                ('status', models.IntegerField(verbose_name='激活状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stime',
        ),
    ]
