# Generated by Django 2.0.1 on 2018-02-15 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180215_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcode',
            name='status',
        ),
    ]
