# Generated by Django 2.0.1 on 2018-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_emailcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='stime',
            field=models.DateTimeField(auto_now=True, verbose_name='生效时间'),
        ),
    ]
