# Generated by Django 2.0.1 on 2018-02-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20180216_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='评论字数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='p_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='app01.Comment', verbose_name='父级评论'),
        ),
    ]
