# Generated by Django 2.0.1 on 2018-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_remove_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='follow_list',
            new_name='followed_list',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.IntegerField(choices=[(1, '管理员'), (2, '普通用户'), (3, 'VIP用户')], default=2, verbose_name='用户类型'),
        ),
    ]
