# Generated by Django 2.0.1 on 2018-02-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_auto_20180217_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='my_fans', to='app01.UserProfile', verbose_name='我的关注'),
        ),
    ]
