# Generated by Django 2.0.1 on 2018-02-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_auto_20180217_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='weibo',
            options={'verbose_name_plural': '微博表'},
        ),
    ]
