# Generated by Django 2.0.1 on 2018-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_auto_20180218_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='readers',
            field=models.IntegerField(default=1, verbose_name='阅读数量'),
        ),
    ]
