# Generated by Django 2.0.1 on 2018-02-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_tags_readers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='readers',
        ),
        migrations.AddField(
            model_name='topic',
            name='readers',
            field=models.IntegerField(default=1, verbose_name='阅读数量'),
        ),
    ]
