# Generated by Django 2.0.1 on 2018-02-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_auto_20180218_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcode',
            name='status',
            field=models.IntegerField(default=0, verbose_name='注册状态'),
        ),
    ]
