# Generated by Django 2.0.1 on 2018-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_emailcode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='status',
            field=models.IntegerField(choices=[(0, '未成功'), (1, '已成功')], default=0, verbose_name='注册状态'),
        ),
    ]
