# Generated by Django 2.0.2 on 2018-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_auto_20180219_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='评论日期'),
        ),
    ]
