# Generated by Django 2.0.2 on 2018-02-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_auto_20180226_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
    ]
