# Generated by Django 2.0.2 on 2018-03-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_auto_20180226_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.IntegerField(choices=[(0, '评论'), (1, '点赞')], default=0),
        ),
    ]
