# Generated by Django 2.0.2 on 2018-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_auto_20180301_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_img_code',
            field=models.CharField(max_length=4, null=True, verbose_name='登陆验证码'),
        ),
    ]
