# Generated by Django 2.0.2 on 2018-03-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_userprofile_login_img_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_img_code',
        ),
    ]
